import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = process.cwd()

function readWorkflow(relativePath: string) {
  return readFileSync(path.join(repoRoot, relativePath), 'utf8')
}

describe('production runtime redeploy workflow', () => {
  it('provides a manual SSH deploy path that runs preflight before optional real load', () => {
    const workflow = readWorkflow('.github/workflows/prod-runtime-redeploy.yml')

    expect(workflow).toContain('workflow_dispatch:')
    expect(workflow).not.toContain('push:')
    expect(workflow).not.toContain('pull_request:')
    expect(workflow).not.toContain('StrictHostKeyChecking=no')
    expect(workflow).toContain('PROD_SSH_HOST: ${{ secrets.PROD_SSH_HOST }}')
    expect(workflow).toContain('PROD_SSH_USER: ${{ secrets.PROD_SSH_USER }}')
    expect(workflow).toContain('PROD_SSH_PRIVATE_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}')
    expect(workflow).toContain('PROD_SSH_KNOWN_HOSTS: ${{ secrets.PROD_SSH_KNOWN_HOSTS }}')
    expect(workflow).toContain('reject_placeholder_secret')
    expect(workflow).toContain('contains a placeholder token; replace it with the real production value')
    expect(workflow).not.toContain('placeholder token: ${value}')
    expect(workflow).toContain('reject_placeholder_secret PROD_SSH_HOST "${PROD_SSH_HOST}"')
    expect(workflow).toContain('reject_placeholder_secret PROD_SSH_USER "${PROD_SSH_USER}"')
    expect(workflow).toContain('reject_placeholder_secret PROD_SSH_PRIVATE_KEY "${PROD_SSH_PRIVATE_KEY}"')
    expect(workflow).toContain('reject_placeholder_secret PROD_SSH_KNOWN_HOSTS "${PROD_SSH_KNOWN_HOSTS}"')
    expect(workflow).toContain('reject_placeholder_secret PROD_SSH_PORT "${PROD_SSH_PORT}"')
    expect(workflow).toContain('ssh-keygen -F "${PROD_SSH_HOST}"')
    expect(workflow).toContain('ghcr.io/kimwoonggon/woong-blog-java-springboot-nextjs-runtime-frontend:main')
    expect(workflow).toContain('ghcr.io/kimwoonggon/woong-blog-java-springboot-nextjs-runtime-backend:main')
    expect(workflow).toContain('REQUIRE_PUBLIC_WORK_VIDEO_CONTRACT=1')
    expect(workflow).toContain('./scripts/prod-runtime-preflight.sh')
    expect(workflow).toContain('tee "${preflight_log}"')
    expect(workflow).toContain('RUN_REAL_LOAD')
    expect(workflow).toContain('./scripts/prod-real-load-steps.sh')
    expect(workflow).toContain('./scripts/prod-runtime-evidence-bundle.sh')
    expect(workflow).toContain('./scripts/prod-runtime-evidence-verify.sh')
    expect(workflow).toContain('PREFLIGHT_LOG="${preflight_log}"')
    expect(workflow).toContain('REAL_LOAD_DIR="${output_dir}"')
    expect(workflow).toContain('repo_digest_for()')
    expect(workflow).toContain('actual_sha="$(git rev-parse HEAD)"')
    expect(workflow).toContain('backend_digest="$(repo_digest_for ghcr.io/kimwoonggon/woong-blog-java-springboot-nextjs-runtime-backend:main)"')
    expect(workflow).toContain('frontend_digest="$(repo_digest_for ghcr.io/kimwoonggon/woong-blog-java-springboot-nextjs-runtime-frontend:main)"')
    expect(workflow).toContain('MAIN_SHA="${actual_sha}"')
    expect(workflow).toContain('BACKEND_IMAGE_DIGEST="${backend_digest}"')
    expect(workflow).toContain('FRONTEND_IMAGE_DIGEST="${frontend_digest}"')
    expect(workflow).toContain('EXPECTED_MAIN_SHA="${actual_sha}"')
    expect(workflow).toContain('EXPECTED_BACKEND_IMAGE_DIGEST="${backend_digest}"')
    expect(workflow).toContain('EXPECTED_FRONTEND_IMAGE_DIGEST="${frontend_digest}"')
    expect(workflow).toContain('"${evidence_dir}/production-runtime-evidence.tar.gz"')
    expect(workflow).toContain('/api/public/works/smoke-fluid-simulation')
    expect(workflow).toContain('/api/public/blogs?page=1&pageSize=12')
    expect(workflow).toContain('reject_seed_path WORK_READ_PATH')
    expect(workflow).toContain('reject_seed_path STUDY_READ_PATH')
    expect(workflow).toContain('prod-real-load-steps-summary.json')
    expect(workflow).toContain('prod-real-load-steps-summary.md')
    expect(workflow).toContain('Real load summary markdown:')
    expect(workflow).toContain('missing expected real load summary artifacts')
    expect(workflow).not.toMatch(/cache/i)

    const allowlist = readWorkflow('scripts/main-runtime-allowlist.txt')
    expect(allowlist).toContain('.github/workflows/prod-runtime-redeploy.yml')
    expect(allowlist).toContain('scripts/prod-runtime-evidence-bundle.sh')
    expect(allowlist).toContain('scripts/prod-runtime-evidence-verify.sh')
  })
})
